<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds with all 50 premium books.
     */
    public function run(): void
    {
        // Disable foreign key checks to allow truncating when related tables exist
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('books')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $books = [
            [
                'id' => 1,
                'title' => 'Belajar React dan Next.js Modern',
                'author' => 'Wicaksono Santoso',
                'category' => 'Teknologi',
                'year' => 2023,
                'shelfLocation' => 'Rak Teknologi T-12',
                'totalCopies' => 5,
                'availableCopies' => 4,
                'synopsis' => 'Panduan lengkap membangun web modern interaktif berbasis sasis React 18, Next.js, dan Tailwind CSS dari dasar hingga mahir.',
                'rating' => 4.8,
                'coverUrl' => 'https://santrikoding.com/storage/courses/3bb3ec62-67a0-4a78-9f0c-f36294e09a3f.webp',
            ],
            [
                'id' => 2,
                'title' => 'Kecerdasan Buatan untuk Kemanusiaan',
                'author' => 'Dr. Eng. Habibie Iskandar',
                'category' => 'Teknologi',
                'year' => 2024,
                'shelfLocation' => 'Rak Teknologi T-15',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Eksplorasi mendalam tentang model bahasa besar, jaringan saraf tiruan, dan bagaimana AI dapat dioptimalkan untuk mempermudah hidup manusia sehari-hari.',
                'rating' => 4.7,
                'coverUrl' => 'https://ugmpress.ugm.ac.id/userfiles/product/Filsafat-Kecerdasan-Buatan-depsn.png',
            ],
            [
                'id' => 3,
                'title' => 'Filosofi Teras: Hidup Tenang ala Stoisisme',
                'author' => 'Henry Manampiring',
                'category' => 'Sastra & Filsafat',
                'year' => 2019,
                'shelfLocation' => 'Rak Sosial S-01',
                'totalCopies' => 8,
                'availableCopies' => 6,
                'synopsis' => 'Buku pengembangan diri praktis yang mengenalkan filsafat Yunani-Romawi kuno (Stoisisme) untuk mengatasi kekhawatiran berlebih di era modern.',
                'rating' => 4.9,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/picture_meta/2023/11/27/kjf6cgigkomf6sy9o5qauu.jpg',
            ],
            [
                'id' => 4,
                'title' => 'Sejarah Ringkas Nusantara',
                'author' => 'Prof. Irwan Mansyur',
                'category' => 'Sejarah',
                'year' => 2021,
                'shelfLocation' => 'Rak Sejarah H-03',
                'totalCopies' => 4,
                'availableCopies' => 2,
                'synopsis' => 'Menelusuri sejarah Indonesia sejak zaman kerajaan Buddha-Hindu, kejayaan Islam, era kolonial, hingga terbentuknya Republik Indonesia modern.',
                'rating' => 4.5,
                'coverUrl' => 'https://divapress-online.com/Files/cover_buku/1738289858_-.jpg',
            ],
            [
                'id' => 5,
                'title' => 'Fisika Kuantum & Misteri Semesta',
                'author' => 'Dian Permana S.Si',
                'category' => 'Sains',
                'year' => 2022,
                'shelfLocation' => 'Rak Sains S-08',
                'totalCopies' => 3,
                'availableCopies' => 2,
                'synopsis' => 'Menguraikan konsep mekanika kuantum yang rumit, paradoks kucing Schrodinger, hingga keterikatan kuantum dalam bahasa populer yang menawan.',
                'rating' => 4.6,
                'coverUrl' => 'https://image.gramedia.net/plain/https://ebooks.gramedia.com/ebook-covers/76764/image_highres/BLK_FK2022243297.jpg',
            ],
            [
                'id' => 6,
                'title' => 'Atomic Habits: Perubahan Kecil untuk Hasil Luar Biasa',
                'author' => 'James Clear (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2020,
                'shelfLocation' => 'Rak Psikologi P-04',
                'totalCopies' => 6,
                'availableCopies' => 5,
                'synopsis' => 'Strategi teruji untuk membentuk kebiasaan baik, menghentikan kebiasaan buruk, dan menguasai perubahan perilaku kecil yang menghasilkan dampak luar biasa.',
                'rating' => 4.9,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/94864/625221008.jpg',
            ],
            [
                'id' => 7,
                'title' => 'Ekonomi Makro di Era Digital',
                'author' => 'Dr. Sri Mulyati',
                'category' => 'Bisnis & Keuangan',
                'year' => 2022,
                'shelfLocation' => 'Rak Bisnis B-09',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Analisis dinamika ekonomi makro global dan dampaknya terhadap startup, ekosistem mata uang kripto, serta inflasi di era serba digital.',
                'rating' => 4.3,
                'coverUrl' => 'https://penerbit.stekom.ac.id/public/journals/12/article_460_cover_en_US.png',
            ],
            [
                'id' => 8,
                'title' => 'Clean Code: Panduan Praktis Menulis Kode yang Bersih',
                'author' => 'Robert C. Martin (Terjemahan)',
                'category' => 'Teknologi',
                'year' => 2018,
                'shelfLocation' => 'Rak Teknologi T-02',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Buku panduan klasik bagi programmer profesional untuk menulis kode yang mudah dibaca, dipelihara, dan diuji.',
                'rating' => 4.9,
                'coverUrl' => 'https://m.media-amazon.com/images/I/81Rnac2Fq+L._SY522_.jpg',
            ],
            [
                'id' => 9,
                'title' => 'Arsitektur Microservices dan Cloud Native',
                'author' => 'Ahmad Rosadi',
                'category' => 'Teknologi',
                'year' => 2023,
                'shelfLocation' => 'Rak Teknologi T-05',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Penjelasan lengkap mengenai desain arsitektur modern menggunakan Docker, Kubernetes, dan Google Cloud Platform.',
                'rating' => 4.6,
                'coverUrl' => 'https://m.media-amazon.com/images/I/81KAJgLnUBL._SY522_.jpg',
            ],
            [
                'id' => 10,
                'title' => 'Cybersecurity untuk Pemula & Pengusaha',
                'author' => 'Budi Raharjo',
                'category' => 'Teknologi',
                'year' => 2022,
                'shelfLocation' => 'Rak Teknologi T-08',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Mengamankan jaringan komputer, server web, dan data pribadi dari serangan siber dengan metode pertahanan terkini.',
                'rating' => 4.5,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/NETWORK_SECURITY_DAN_CYBER_SECURITY_DVD.png',
            ],
            [
                'id' => 11,
                'title' => 'Dasar Pemrograman Python untuk Sains Data',
                'author' => 'Teguh Wahyono',
                'category' => 'Teknologi',
                'year' => 2021,
                'shelfLocation' => 'Rak Teknologi T-10',
                'totalCopies' => 6,
                'availableCopies' => 5,
                'synopsis' => 'Langkah mudah memahami sintaks Python, manipulasi data menggunakan Pandas, NumPy, serta visualisasi data dasar.',
                'rating' => 4.7,
                'coverUrl' => 'https://cvalfabeta.com/wp-content/uploads/2025/06/SigitS-DasarBhsPemrograman125-Cover-667x1024.jpg',
            ],
            [
                'id' => 12,
                'title' => 'Desain UI/UX: Prototyping Menawan dengan Figma',
                'author' => 'Rian Adriadi',
                'category' => 'Teknologi',
                'year' => 2024,
                'shelfLocation' => 'Rak Teknologi T-14',
                'totalCopies' => 5,
                'availableCopies' => 4,
                'synopsis' => 'Menyelami teknik user research, wireframing, pembuatan sistem desain, hingga prototipe interaktif modern di Figma.',
                'rating' => 4.8,
                'coverUrl' => 'https://openlibrary.telkomuniversity.ac.id/uploads/book/cover/24.01.910.jpg',
            ],
            [
                'id' => 13,
                'title' => 'Membangun Aplikasi Android dengan Kotlin dan Jetpack Compose',
                'author' => 'Yudha Pratama',
                'category' => 'Teknologi',
                'year' => 2023,
                'shelfLocation' => 'Rak Teknologi T-16',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Panduan implementasi arsitektur Model-View-ViewModel (MVVM) modern untuk aplikasi Android berkinerja tinggi.',
                'rating' => 4.7,
                'coverUrl' => 'https://m.media-amazon.com/images/I/411IvRPcA9L._SY445_SX342_QL70_FMwebp_.jpg',
            ],
            [
                'id' => 14,
                'title' => 'Blockchain & Smart Contracts: Teori dan Implementasi',
                'author' => 'Irvan Gunawan',
                'category' => 'Teknologi',
                'year' => 2022,
                'shelfLocation' => 'Rak Teknologi T-18',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Membahas cara kerja rantai blok, konsensus terdistribusi, serta pemrograman smart contract menggunakan Solidity.',
                'rating' => 4.4,
                'coverUrl' => 'https://m.media-amazon.com/images/I/61XJZJZJZJL._SY522_.jpg',
            ],
            [
                'id' => 15,
                'title' => 'Cosmos: Menjelajahi Batas Waktu dan Ruang',
                'author' => 'Carl Sagan (Terjemahan)',
                'category' => 'Sains',
                'year' => 1995,
                'shelfLocation' => 'Rak Sains S-02',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'synopsis' => 'Salah satu karya sains terpopuler sepanjang masa yang membahas hubungan antara peradaban manusia dan luasnya kosmos.',
                'rating' => 4.9,
                'coverUrl' => 'https://miro.medium.com/v2/resize:fit:1100/format:webp/1*RUdxg8mvydBeck3Mq1m38g.jpeg',
            ],
            [
                'id' => 16,
                'title' => 'Asal-usul Spesies (The Origin of Species)',
                'author' => 'Charles Darwin (Terjemahan)',
                'category' => 'Sains',
                'year' => 2015,
                'shelfLocation' => 'Rak Sains S-04',
                'totalCopies' => 2,
                'availableCopies' => 2,
                'synopsis' => 'Buku legendaris yang merumuskan dasar teori evolusi melalui seleksi alam dan adaptasi makhluk hidup terhadap lingkungan.',
                'rating' => 4.4,
                'coverUrl' => 'https://image.gramedia.net/plain/https://ebooks.gramedia.com/ebook-covers/3327/big_covers/ID_GPU2013MTH04ASOTOOS_B.jpg',
            ],
            [
                'id' => 17,
                'title' => 'Gen: Riwayat Intim tentang Rahasia Kehidupan',
                'author' => 'Siddhartha Mukherjee (Terjemahan)',
                'category' => 'Sains',
                'year' => 2018,
                'shelfLocation' => 'Rak Sains S-05',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Kisah menakjubkan tentang penemuan gen, kode genetik manusia, fajar bioteknologi, hingga perdebatan moral rekayasa genetika.',
                'rating' => 4.8,
                'coverUrl' => 'https://penerbitnilacakra.com/wp-content/uploads/2024/07/rahasia-seri-pendidikan-seksual-untuk-anak-cover-e1724288510209.webp',
            ],
            [
                'id' => 18,
                'title' => 'Pengantar Astronomi & Astrofisika Modern',
                'author' => 'Dr. Thomas Djamaluddin',
                'category' => 'Sains',
                'year' => 2021,
                'shelfLocation' => 'Rak Sains S-09',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Mempelajari fisika bintang, galaksi, lubang hitam, sejarah terbentuknya tata surya, dan kosmologi modern.',
                'rating' => 4.6,
                'coverUrl' => 'https://i0.wp.com/agosbookstore.com/wp-content/uploads/2022/06/177547b5-dce7-4a83-82e9-152051a6ff94.jpg?fit=700%2C1000&ssl=1',
            ],
            [
                'id' => 19,
                'title' => 'Biokimia Dasar: Memahami Process Kimiawi Tubuh',
                'author' => 'Prof. Endang Sukara',
                'category' => 'Sains',
                'year' => 2020,
                'shelfLocation' => 'Rak Sains S-11',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Penjelasan terperinci mengenai metabolisme sel, enzim, protein, DNA/RNA, serta keterkaitannya dengan kesehatan manusia.',
                'rating' => 4.5,
                'coverUrl' => 'https://i1.rgstatic.net/publication/403605018_BIOKIMIA_DASAR/links/69d5be6fb6bee42358236110/smallpreview.png',
            ],
            [
                'id' => 20,
                'title' => 'Teori Relativitas Einstein untuk Orang Awam',
                'author' => 'Albert Einstein (Terjemahan)',
                'category' => 'Sains',
                'year' => 2017,
                'shelfLocation' => 'Rak Sains S-07',
                'totalCopies' => 5,
                'availableCopies' => 4,
                'synopsis' => 'Ditulis langsung oleh sang penemu untuk menjelaskan relativitas khusus dan umum tanpa rumus matematika yang rumit.',
                'rating' => 4.8,
                'coverUrl' => 'https://tirtabuanamedia.co.id/wp-content/uploads/2023/01/Teori-Relativitas-Einstein.jpg',
            ],
            [
                'id' => 21,
                'title' => 'Ekologi & Perubahan Iklim Global',
                'author' => 'Dr. Emil Salim',
                'category' => 'Sains',
                'year' => 2019,
                'shelfLocation' => 'Rak Sains S-15',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Analisis dampak pemanasan global terhadap keanekaragaman hayati Indonesia serta pentingnya pembangunan berkelanjutan.',
                'rating' => 4.3,
                'coverUrl' => 'https://i0.wp.com/agosbookstore.com/wp-content/uploads/2022/06/65efdbe9-63be-4834-a9eb-332cfd81c253.jpg?fit=700%2C1039&ssl=1',
            ],
            [
                'id' => 22,
                'title' => 'Sapiens: Riwayat Singkat Umat Manusia',
                'author' => 'Yuval Noah Harari (Terjemahan)',
                'category' => 'Sejarah',
                'year' => 2017,
                'shelfLocation' => 'Rak Sejarah H-01',
                'totalCopies' => 10,
                'availableCopies' => 10,
                'synopsis' => 'Buku fenomenal yang merangkum sejarah peradaban manusia sejak zaman revolusi kognitif hingga era bioteknologi modern.',
                'rating' => 4.9,
                'coverUrl' => 'https://e-library.banjarmasinkota.go.id/storage/book_cover/1665980469_4084.jpeg',
            ],
            [
                'id' => 23,
                'title' => 'Gajah Mada: Biografi Politik Sang Mahapatih',
                'author' => 'Muhammad Yamin',
                'category' => 'Sejarah',
                'year' => 2018,
                'shelfLocation' => 'Rak Sejarah H-04',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Analisis historis kepemimpinan Gajah Mada dalam mewujudkan Sumpah Palapa untuk mempersatukan wilayah Nusantara di bawah Majapahit.',
                'rating' => 4.6,
                'coverUrl' => 'https://perpustakaan.jakarta.go.id/catalog-dispusip/uploaded_files/sampul_koleksi/original/Monograf/111102.jpg',
            ],
            [
                'id' => 24,
                'title' => 'Jalur Rempah: Jejak Peradaban Dunia di Nusantara',
                'author' => 'Taufik Abdullah',
                'category' => 'Sejarah',
                'year' => 2021,
                'shelfLocation' => 'Rak Sejarah H-07',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Menyingkap sejarah perdagangan rempah-rempah yang menempatkan kepulauan Nusantara sebagai poros diplomasi dan kolonialisme barat.',
                'rating' => 4.7,
                'coverUrl' => 'https://bintangpusnas.perpusnas.go.id/api25/public/api/get-image/48115_prod_be6dbf13f60c19722ba6227827ca2708.png',
            ],
            [
                'id' => 25,
                'title' => 'Sejarah Dunia yang Disembunyikan',
                'author' => 'Jonathan Black (Terjemahan)',
                'category' => 'Sejarah',
                'year' => 2015,
                'shelfLocation' => 'Rak Sejarah H-10',
                'totalCopies' => 8,
                'availableCopies' => 8,
                'synopsis' => 'Menyelidiki berbagai mitos kuno, perkumpulan rahasia, serta penafsiran sejarah alternatif dari sudut pandang hermetisisme.',
                'rating' => 4.5,
                'coverUrl' => 'https://perpustakaan.jakarta.go.id/catalog-dispusip/uploaded_files/sampul_koleksi/original/Monograf/121437.jpg',
            ],
            [
                'id' => 26,
                'title' => 'Bung Karno: Penyambung Lidah Rakyat Indonesia',
                'author' => 'Cindy Adams',
                'category' => 'Sejarah',
                'year' => 2014,
                'shelfLocation' => 'Rak Sejarah H-02',
                'totalCopies' => 6,
                'availableCopies' => 5,
                'synopsis' => 'Otobiografi resmi Presiden pertama Indonesia yang menceritakan perjuangan masa muda, pengasingan, hingga proklamasi kemerdekaan.',
                'rating' => 4.9,
                'coverUrl' => 'https://bukukita.com/babacms/displaybuku/96286_f.jpg',
            ],
            [
                'id' => 27,
                'title' => 'Kerajaan-kerajaan Islam di Jawa',
                'author' => 'Dr. Slamet Muljana',
                'category' => 'Sejarah',
                'year' => 2019,
                'shelfLocation' => 'Rak Sejarah H-09',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Eksplorasi berdirinya Demak, Pajang, Mataram, Cirebon, hingga Banten, serta proses asimilasi budaya lokal dengan ajaran Islam.',
                'rating' => 4.5,
                'coverUrl' => 'https://bukuaudio.org/epub/2016/10/kerajaan-islam-di-jawa.jpg',
            ],
            [
                'id' => 28,
                'title' => 'Revolusi Prancis: Lahirnya Demokrasi Modern',
                'author' => 'Jean-Pierre Roux (Terjemahan)',
                'category' => 'Sejarah',
                'year' => 2016,
                'shelfLocation' => 'Rak Sejarah H-12',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Menceritakan tumbangnya monarki absolut Prancis di tahun 1789 yang merestrukturisasi sistem sosial-politik dunia secara masif.',
                'rating' => 4.4,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/95086/625222038.jpg',
            ],
            [
                'id' => 29,
                'title' => 'Bumi Manusia',
                'author' => 'Pramoedya Ananta Toer',
                'category' => 'Sastra & Filsafat',
                'year' => 2005,
                'shelfLocation' => 'Rak Sastra S-02',
                'totalCopies' => 12,
                'availableCopies' => 11,
                'synopsis' => 'Karya agung sastra Indonesia berlatar awal abad ke-20 yang menceritakan kisah cinta Minke dan Annelies di tengah pergulatan kolonial.',
                'rating' => 4.9,
                'coverUrl' => 'https://upload.wikimedia.org/wikipedia/id/5/51/Bumi_Manusia_poster.jpg',
            ],
            [
                'id' => 30,
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'category' => 'Sastra & Filsafat',
                'year' => 2005,
                'shelfLocation' => 'Rak Sastra S-04',
                'totalCopies' => 10,
                'availableCopies' => 9,
                'synopsis' => 'Kisah mengharukan tentang perjuangan sepuluh anak di Belitung dalam menempuh pendidikan di sekolah swasta yang serba terbatas.',
                'rating' => 4.8,
                'coverUrl' => 'https://upload.wikimedia.org/wikipedia/id/8/8e/Laskar_pelangi_sampul.jpg',
            ],
            [
                'id' => 31,
                'title' => 'Cantik Itu Luka',
                'author' => 'Eka Kurniawan',
                'category' => 'Sastra & Filsafat',
                'year' => 2015,
                'shelfLocation' => 'Rak Sastra S-06',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Sebuah novel realisme magis kompleks yang menelusuri sejarah kelam peperangan, patriarki, dan keturunan peradaban di Indonesia.',
                'rating' => 4.7,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/93810/622202017.jpg',
            ],
            [
                'id' => 32,
                'title' => "Dunia Sophie (Sophie's World)",
                'author' => 'Jostein Gaarder (Terjemahan)',
                'category' => 'Sastra & Filsafat',
                'year' => 2010,
                'shelfLocation' => 'Rak Sastra S-08',
                'totalCopies' => 7,
                'availableCopies' => 6,
                'synopsis' => 'Novel filsafat yang membawa pembaca dalam perjalanan menjelajahi sejarah pemikiran filsuf barat dari masa Yunani kuno hingga fajar abad ke-20.',
                'rating' => 4.8,
                'coverUrl' => 'https://bukukita.com/babacms/displaybuku/100330_f.jpg',
            ],
            [
                'id' => 33,
                'title' => 'Madilog: Materialisme, Dialektika, Logika',
                'author' => 'Tan Malaka',
                'category' => 'Sastra & Filsafat',
                'year' => 2014,
                'shelfLocation' => 'Rak Sosial S-03',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Karya filsafat monumentil Tan Malaka yang memandu bangsa Indonesia untuk berpikir rasional dan ilmiah guna melepaskan diri dari mistisisme.',
                'rating' => 4.6,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/picture_meta/2024/6/3/kvmiih4eluib7d2w2x9zmh.jpg',
            ],
            [
                'id' => 34,
                'title' => 'Saman',
                'author' => 'Ayu Utami',
                'category' => 'Sastra & Filsafat',
                'year' => 1998,
                'shelfLocation' => 'Rak Sastra S-10',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Novel pemenang penghargaan yang membahas tentang seksualitas perempuan, kebebasan, perjuangan buruh, dan represi politik Orde Baru.',
                'rating' => 4.5,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/picture_meta/2023/2/28/3u4gvnfpk5bxw2zxwwzsrm.jpg',
            ],
            [
                'id' => 35,
                'title' => 'Ronggeng Dukuh Paruk',
                'author' => 'Ahmad Tohari',
                'category' => 'Sastra & Filsafat',
                'year' => 2003,
                'shelfLocation' => 'Rak Sastra S-05',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'synopsis' => 'Trilogi novel sosiokultural yang mengisahkan Srintil and Rasus dengan latar kehidupan dusun miskin yang luluh lantak akibat konflik politik 1965.',
                'rating' => 4.8,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/product-metas/uh0d0g8ukg.jpg',
            ],
            [
                'id' => 36,
                'title' => 'Hujan Bulan Juni: Kumpulan Puisi',
                'author' => 'Sapardi Djoko Damono',
                'category' => 'Sastra & Filsafat',
                'year' => 2015,
                'shelfLocation' => 'Rak Sastra S-01',
                'totalCopies' => 8,
                'availableCopies' => 8,
                'synopsis' => 'Koleksi puisi cinta liris paling romantis dan bersahaja dalam sastra Indonesia modern yang penuh kedalaman makna hidup.',
                'rating' => 4.9,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/picture_meta/2024/6/3/kvmiih4eluib7d2w2x9zmh.jpg',
            ],
            [
                'id' => 37,
                'title' => 'Berani Tidak Disukai',
                'author' => 'Ichiro Kishimi & Fumitake Koga (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2019,
                'shelfLocation' => 'Rak Psikologi P-01',
                'totalCopies' => 9,
                'availableCopies' => 9,
                'synopsis' => 'Panduan psikologi Adlerian yang mengajari kita melepaskan diri dari penilaian orang lain, berdamai dengan trauma, dan meraih kebebasan sejati.',
                'rating' => 4.8,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/93954/623221003.jpg',
            ],
            [
                'id' => 38,
                'title' => 'Grit: Kekuatan Passion dan Kegigihan',
                'author' => 'Angela Duckworth (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2018,
                'shelfLocation' => 'Rak Psikologi P-03',
                'totalCopies' => 5,
                'availableCopies' => 4,
                'synopsis' => 'Menunjukkan bahwa kunci kesuksesan jangka panjang bukanlah bakat murni, melainkan kombinasi istimewa antara ketabahan dan hasrat (Grit).',
                'rating' => 4.6,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/93995/623221005.jpg',
            ],
            [
                'id' => 39,
                'title' => "Man's Search for Meaning",
                'author' => 'Viktor E. Frankl (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2017,
                'shelfLocation' => 'Rak Psikologi P-06',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'synopsis' => 'Buku legendaris tulisan psikiater penyintas kamp konsentrasi Nazi tentang pentingnya menemukan makna hidup dalam penderitaan terpahit sekalipun.',
                'rating' => 4.9,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/a7nxmvsx-e.jpeg',
            ],
            [
                'id' => 40,
                'title' => 'Think and Grow Rich: Berpikir dan Menjadi Kaya',
                'author' => 'Napoleon Hill (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2016,
                'shelfLocation' => 'Rak Psikologi P-08',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Formula sukses legendaris yang merangkum kebiasaan orang-orang terkaya di dunia untuk mengubah hasrat mental menjadi kenyataan fisik.',
                'rating' => 4.5,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/9786230405990_Think_and_Grow_Rich.jpeg',
            ],
            [
                'id' => 41,
                'title' => 'Mindset: Mengubah Pola Pikir untuk Perubahan Besar',
                'author' => 'Carol S. Dweck (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2018,
                'shelfLocation' => 'Rak Psikologi P-02',
                'totalCopies' => 7,
                'availableCopies' => 6,
                'synopsis' => 'Mengembangkan perbedaan pola pikir tetap (fixed mindset) vs pola pikir berkembang (growth mindset) yang membentuk kesuksesan hidup.',
                'rating' => 4.7,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/icc53z5mei.jpg',
            ],
            [
                'id' => 42,
                'title' => 'Seni Berbicara di Depan Umum: Public Speaking',
                'author' => 'Dale Carnegie (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2015,
                'shelfLocation' => 'Rak Psikologi P-10',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'synopsis' => 'Metode praktis mengatasi rasa takut, melatih artikulasi, serta menarik simpati pendengar dalam komunikasi profesional dan interpersonal.',
                'rating' => 4.6,
                'coverUrl' => 'https://penerbitmadza.com/wp-content/uploads/2024/08/The-Art-Public-Speaking-Menyampaikan-Pesan-yang-Berkesan-scaled.jpg',
            ],
            [
                'id' => 43,
                'title' => 'Ikigai: Rahasia Hidup Bahagia & Panjang Umur ala Jepang',
                'author' => 'Héctor García (Terjemahan)',
                'category' => 'Pengembangan Diri',
                'year' => 2019,
                'shelfLocation' => 'Rak Psikologi P-05',
                'totalCopies' => 8,
                'availableCopies' => 8,
                'synopsis' => 'Eksplorasi konsep Ikigai, yaitu pertemuan antara hasrat, misi, pekerjaan, dan keahlian untuk menemukan alasan bangun di pagi hari.',
                'rating' => 4.7,
                'coverUrl' => 'https://assets.kompasiana.com/items/album/2023/08/04/rich-dad-poor-dad-cover-64ccb2814addee2ff81aefb2.jpg?t=o&v=740&x=416',
            ],
            [
                'id' => 44,
                'title' => 'Rich Dad Poor Dad: Mengajarkan Keuangan pada Anak',
                'author' => 'Robert T. Kiyosaki (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2016,
                'shelfLocation' => 'Rak Bisnis B-01',
                'totalCopies' => 8,
                'availableCopies' => 8,
                'synopsis' => 'Mengunggap miskonsepsi besar tentang kekayaan, perbedaan aset vs liabilitas, dan bagaimana membiarkan uang bekerja keras untuk kita.',
                'rating' => 4.8,
                'coverUrl' => 'https://gpu.id/data-gpu/images/img-book/94906/625203007.jpg',
            ],
            [
                'id' => 45,
                'title' => 'The Intelligent Investor: Rekomendasi Investasi Nilai',
                'author' => 'Benjamin Graham (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2018,
                'shelfLocation' => 'Rak Bisnis B-04',
                'totalCopies' => 4,
                'availableCopies' => 4,
                'synopsis' => 'Alkitab perdagangan saham legendaris yang memaparkan prinsip value investing demi menghindari jebakan bursa dan risiko pasar besar.',
                'rating' => 4.7,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/Intelligent_Investor_The.jpg',
            ],
            [
                'id' => 46,
                'title' => 'Zero to One: Catatan tentang Startup',
                'author' => 'Peter Thiel (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2015,
                'shelfLocation' => 'Rak Bisnis B-02',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Membahas pentingnya menciptakan inovasi baru yang mengubah monopoli industri dan menciptakan masa depan dari nol menjadi satu.',
                'rating' => 4.6,
                'coverUrl' => 'https://image.gramedia.net/plain/https://ebooks.gramedia.com/ebook-covers/99198/image_highres/BLK_ZTOS21738026733861.jpg',
            ],
            [
                'id' => 47,
                'title' => 'The Lean Startup: Memulai Bisnis Modern dengan Efisien',
                'author' => 'Eric Ries (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2016,
                'shelfLocation' => 'Rak Bisnis B-05',
                'totalCopies' => 6,
                'availableCopies' => 6,
                'synopsis' => 'Kerangka manajemen inovatif menggunakan iterasi cepat, Minimum Viable Product (MVP), dan pembelajaran terukur dalam startup.',
                'rating' => 4.7,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/The_Lean_Startup.jpg',
            ],
            [
                'id' => 48,
                'title' => 'Good to Great: Mengapa Ada Perusahaan Lompat Kelas',
                'author' => 'Jim Collins (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2017,
                'shelfLocation' => 'Rak Bisnis B-07',
                'totalCopies' => 3,
                'availableCopies' => 3,
                'synopsis' => 'Penelitian mendalam tentang bagaimana perusahaan biasa-biasa saja bertransformasi menjadi perusahaan raksasa yang bertahan puluhan tahun.',
                'rating' => 4.6,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/picture_meta/2022/12/5/6uvrurklaulrsxsavgv7yk.jpg',
            ],
            [
                'id' => 49,
                'title' => 'Psychology of Money: Pelajaran Abadi tentang Keuangan',
                'author' => 'Morgan Housel (Terjemahan)',
                'category' => 'Bisnis & Keuangan',
                'year' => 2021,
                'shelfLocation' => 'Rak Bisnis B-10',
                'totalCopies' => 10,
                'availableCopies' => 9,
                'synopsis' => 'Eksplorasi perilaku emosional manusia terhadap uang, ego, keserakahan, serta cara bijak mengelola kekayaan berkelanjutan.',
                'rating' => 4.9,
                'coverUrl' => 'https://bukuaudio.org/daisy/2024/07/_cover/cover_the_psychology_of_money.jpg',
            ],
            [
                'id' => 50,
                'title' => 'Pemasaran 5.0: Teknologi untuk Kemanusiaan',
                'author' => 'Philip Kotler & Hermawan Kartajaya',
                'category' => 'Bisnis & Keuangan',
                'year' => 2021,
                'shelfLocation' => 'Rak Bisnis B-03',
                'totalCopies' => 5,
                'availableCopies' => 5,
                'synopsis' => 'Mengintegrasikan taktik pemasaran manusiawi dengan teknologi mutakhir (AI, big data, AR/VR) untuk memenangkan persaingan bisnis digital.',
                'rating' => 4.8,
                'coverUrl' => 'https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/Marketing_5_0_C_1_4_1_page-0001.jpg',
            ],
        ];

        foreach ($books as $book) {
            DB::table('books')->updateOrInsert(['id' => $book['id']], $book);
        }
    }
}
