-- Database: perpustakaan
-- Buat struktur database perpustakaan untuk phpMyAdmin lengkap dengan 50 Koleksi Buku Real-Time

CREATE DATABASE IF NOT EXISTS `perpustakaan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `perpustakaan`;

-- --------------------------------------------------------

-- Struktur dari tabel `books`
CREATE TABLE IF NOT EXISTS `books` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `author` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL,
  `year` int(11) NOT NULL,
  `shelfLocation` varchar(255) NOT NULL,
  `totalCopies` int(11) NOT NULL,
  `availableCopies` int(11) NOT NULL,
  `synopsis` text NOT NULL,
  `rating` decimal(3,1) NOT NULL DEFAULT 5.0,
  `coverUrl` varchar(500) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data untuk tabel `books` dengan semua 50 buku dari sasis sistem utama
INSERT INTO `books` (`id`, `title`, `author`, `category`, `year`, `shelfLocation`, `totalCopies`, `availableCopies`, `synopsis`, `rating`, `coverUrl`, `created_at`, `updated_at`) VALUES
(1, 'Belajar React dan Next.js Modern', 'Wicaksono Santoso', 'Teknologi', 2023, 'Rak Teknologi T-12', 5, 4, 'Panduan lengkap membangun web modern interaktif berbasis sasis React 18, Next.js, dan Tailwind CSS dari dasar hingga mahir.', 4.8, 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(2, 'Kecerdasan Buatan untuk Kemanusiaan', 'Dr. Eng. Habibie Iskandar', 'Teknologi', 2024, 'Rak Teknologi T-15', 3, 3, 'Eksplorasi mendalam tentang model bahasa besar, jaringan saraf tiruan, dan bagaimana AI dapat dioptimalkan untuk mempermudah hidup manusia sehari-hari.', 4.7, 'https://images.unsplash.com/photo-1677442136019-21780efad99a?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(3, 'Filosofi Teras: Hidup Tenang ala Stoisisme', 'Henry Manampiring', 'Sastra & Filsafat', 2019, 'Rak Sosial S-01', 8, 6, 'Buku pengembangan diri praktis yang mengenalkan filsafat Yunani-Romawi kuno (Stoisisme) untuk mengatasi kekhawatiran berlebih di era modern.', 4.9, 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(4, 'Sejarah Ringkas Nusantara', 'Prof. Irwan Mansyur', 'Sejarah', 2021, 'Rak Sejarah H-03', 4, 2, 'Menelusuri sejarah Indonesia sejak zaman kerajaan Buddha-Hindu, kejayaan Islam, era kolonial, hingga terbentuknya Republik Indonesia modern.', 4.5, 'https://images.unsplash.com/photo-1505993597083-3bd19f7c3f3d?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(5, 'Fisika Kuantum & Misteri Semesta', 'Dian Permana S.Si', 'Sains', 2022, 'Rak Sains S-08', 3, 2, 'Menguraikan konsep mekanika kuantum yang rumit, paradoks kucing Schrodinger, hingga keterikatan kuantum dalam bahasa populer yang menawan.', 4.6, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(6, 'Atomic Habits: Perubahan Kecil untuk Hasil Luar Biasa', 'James Clear (Terjemahan)', 'Pengembangan Diri', 2020, 'Rak Psikologi P-04', 6, 5, 'Strategi teruji untuk membentuk kebiasaan baik, menghentikan kebiasaan buruk, dan menguasai perubahan perilaku kecil yang menghasilkan dampak luar biasa.', 4.9, 'https://images.unsplash.com/photo-1506784983877-45594efa4cbe?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(7, 'Ekonomi Makro di Era Digital', 'Dr. Sri Mulyati', 'Bisnis & Keuangan', 2022, 'Rak Bisnis B-09', 4, 4, 'Analisis dinamika ekonomi makro global dan dampaknya terhadap startup, ekosistem mata uang kripto, serta inflasi di era serba digital.', 4.3, 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(8, 'Clean Code: Panduan Praktis Menulis Kode yang Bersih', 'Robert C. Martin (Terjemahan)', 'Teknologi', 2018, 'Rak Teknologi T-02', 5, 5, 'Buku panduan klasik bagi programmer profesional untuk menulis kode yang mudah dibaca, dipelihara, dan diuji.', 4.9, 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(9, 'Arsitektur Microservices dan Cloud Native', 'Ahmad Rosadi', 'Teknologi', 2023, 'Rak Teknologi T-05', 4, 4, 'Penjelasan lengkap mengenai desain arsitektur modern menggunakan Docker, Kubernetes, dan Google Cloud Platform.', 4.6, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(10, 'Cybersecurity untuk Pemula & Pengusaha', 'Budi Raharjo', 'Teknologi', 2022, 'Rak Teknologi T-08', 3, 3, 'Mengamankan jaringan komputer, server web, dan data pribadi dari serangan siber dengan metode pertahanan terkini.', 4.5, 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(11, 'Dasar Pemrograman Python untuk Sains Data', 'Teguh Wahyono', 'Teknologi', 2021, 'Rak Teknologi T-10', 6, 5, 'Langkah mudah memahami sintaks Python, manipulasi data menggunakan Pandas, NumPy, serta visualisasi data dasar.', 4.7, 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(12, 'Desain UI/UX: Prototyping Menawan dengan Figma', 'Rian Adriadi', 'Teknologi', 2024, 'Rak Teknologi T-14', 5, 4, 'Menyelami teknik user research, wireframing, pembuatan sistem desain, hingga prototipe interaktif modern di Figma.', 4.8, 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(13, 'Membangun Aplikasi Android dengan Kotlin dan Jetpack Compose', 'Yudha Pratama', 'Teknologi', 2023, 'Rak Teknologi T-16', 3, 3, 'Panduan implementasi arsitektur Model-View-ViewModel (MVVM) modern untuk aplikasi Android berkinerja tinggi.', 4.7, 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(14, 'Blockchain & Smart Contracts: Teori dan Implementasi', 'Irvan Gunawan', 'Teknologi', 2022, 'Rak Teknologi T-18', 4, 4, 'Membahas cara kerja rantai blok, konsensus terdistribusi, serta pemrograman smart contract menggunakan Solidity.', 4.4, 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(15, 'Cosmos: Menjelajahi Batas Waktu dan Ruang', 'Carl Sagan (Terjemahan)', 'Sains', 1995, 'Rak Sains S-02', 6, 6, 'Salah satu karya sains terpopuler sepanjang masa yang membahas hubungan antara peradaban manusia dan luasnya kosmos.', 4.9, 'https://images.unsplash.com/photo-1464802686167-b939a6910659?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(16, 'Asal-usul Spesies (The Origin of Species)', 'Charles Darwin (Terjemahan)', 'Sains', 2015, 'Rak Sains S-04', 2, 2, 'Buku legendaris yang merumuskan dasar teori evolusi melalui seleksi alam dan adaptasi makhluk hidup terhadap lingkungan.', 4.4, 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(17, 'Gen: Riwayat Intim tentang Rahasia Kehidupan', 'Siddhartha Mukherjee (Terjemahan)', 'Sains', 2018, 'Rak Sains S-05', 4, 4, 'Kisah menakjubkan tentang penemuan gen, kode genetik manusia, fajar bioteknologi, hingga perdebatan moral rekayasa genetika.', 4.8, 'https://images.unsplash.com/photo-1530026405186-ed1ea0ac7a63?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(18, 'Pengantar Astronomi & Astrofisika Modern', 'Dr. Thomas Djamaluddin', 'Sains', 2021, 'Rak Sains S-09', 3, 3, 'Mempelajari fisika bintang, galaksi, lubang hitam, sejarah terbentuknya tata surya, dan kosmologi modern.', 4.6, 'https://images.unsplash.com/photo-1506318137071-a8e063b4bec0?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(19, 'Biokimia Dasar: Memahami Process Kimiawi Tubuh', 'Prof. Endang Sukara', 'Sains', 2020, 'Rak Sains S-11', 4, 4, 'Penjelasan terperinci mengenai metabolisme sel, enzim, protein, DNA/RNA, serta keterkaitannya dengan kesehatan manusia.', 4.5, 'https://images.unsplash.com/photo-1532187863486-abf9d39d66e8?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(20, 'Teori Relativitas Einstein untuk Orang Awam', 'Albert Einstein (Terjemahan)', 'Sains', 2017, 'Rak Sains S-07', 5, 4, 'Ditulis langsung oleh sang penemu untuk menjelaskan relativitas khusus dan umum tanpa rumus matematika yang rumit.', 4.8, 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(21, 'Ekologi & Perubahan Iklim Global', 'Dr. Emil Salim', 'Sains', 2019, 'Rak Sains S-15', 4, 4, 'Analisis dampak pemanasan global terhadap keanekaragaman hayati Indonesia serta pentingnya pembangunan berkelanjutan.', 4.3, 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(22, 'Sapiens: Riwayat Singkat Umat Manusia', 'Yuval Noah Harari (Terjemahan)', 'Sejarah', 2017, 'Rak Sejarah H-01', 10, 10, 'Buku fenomenal yang merangkum sejarah peradaban manusia sejak zaman revolusi kognitif hingga era bioteknologi modern.', 4.9, 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(23, 'Gajah Mada: Biografi Politik Sang Mahapatih', 'Muhammad Yamin', 'Sejarah', 2018, 'Rak Sejarah H-04', 5, 5, 'Analisis historis kepemimpinan Gajah Mada dalam mewujudkan Sumpah Palapa untuk mempersatukan wilayah Nusantara di bawah Majapahit.', 4.6, 'https://images.unsplash.com/photo-1596402184320-417e7178b2cd?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(24, 'Jalur Rempah: Jejak Peradaban Dunia di Nusantara', 'Taufik Abdullah', 'Sejarah', 2021, 'Rak Sejarah H-07', 4, 4, 'Menyingkap sejarah perdagangan rempah-rempah yang menempatkan kepulauan Nusantara sebagai poros diplomasi dan kolonialisme barat.', 4.7, 'https://images.unsplash.com/photo-1596797038530-2c107229654b?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(25, 'Sejarah Dunia yang Disembunyikan', 'Jonathan Black (Terjemahan)', 'Sejarah', 2015, 'Rak Sejarah H-10', 8, 8, 'Menyelidiki berbagai mitos kuno, perkumpulan rahasia, serta penafsiran sejarah alternatif dari sudut pandang hermetisisme.', 4.5, 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(26, 'Bung Karno: Penyambung Lidah Rakyat Indonesia', 'Cindy Adams', 'Sejarah', 2014, 'Rak Sejarah H-02', 6, 5, 'Otobiografi resmi Presiden pertama Indonesia yang menceritakan perjuangan masa muda, pengasingan, hingga proklamasi kemederkaan.', 4.9, 'https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(27, 'Kerajaan-kerajaan Islam di Jawa', 'Dr. Slamet Muljana', 'Sejarah', 2019, 'Rak Sejarah H-09', 3, 3, 'Eksplorasi berdirinya Demak, Pajang, Mataram, Cirebon, hingga Banten, serta proses asimilasi budaya lokal dengan ajaran Islam.', 4.5, 'https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(28, 'Revolusi Prancis: Lahirnya Demokrasi Modern', 'Jean-Pierre Roux (Terjemahan)', 'Sejarah', 2016, 'Rak Sejarah H-12', 4, 4, 'Menceritakan tumbangnya monarki absolut Prancis di tahun 1789 yang merestrukturisasi sistem sosial-politik dunia secara masif.', 4.4, 'https://images.unsplash.com/photo-1499195333224-3ce974eecb47?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(29, 'Bumi Manusia', 'Pramoedya Ananta Toer', 'Sastra & Filsafat', 2005, 'Rak Sastra S-02', 12, 11, 'Karya agung sastra Indonesia berlatar awal abad ke-20 yang menceritakan kisah cinta Minke dan Annelies di tengah pergulatan kolonial.', 4.9, 'https://images.unsplash.com/photo-1516979187457-637abb4f9353?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(30, 'Laskar Pelangi', 'Andrea Hirata', 'Sastra & Filsafat', 2005, 'Rak Sastra S-04', 10, 9, 'Kisah mengharukan tentang perjuangan sepuluh anak di Belitung dalam menempuh pendidikan di sekolah swasta yang serba terbatas.', 4.8, 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(31, 'Cantik Itu Luka', 'Eka Kurniawan', 'Sastra & Filsafat', 2015, 'Rak Sastra S-06', 5, 5, 'Sebuah novel realisme magis kompleks yang menelusuri sejarah kelam peperangan, patriarki, dan keturunan peradaban di Indonesia.', 4.7, 'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?q=85&w=600&auto=format&fit=crop', NULL, NULL),
(32, 'Dunia Sophie (Sophie\'s World)', 'Jostein Gaarder (Terjemahan)', 'Sastra & Filsafat', 2010, 'Rak Sastra S-08', 7, 6, 'Novel filsafat yang membawa pembaca dalam perjalanan menjelajahi sejarah pemikiran filsuf barat dari masa Yunani kuno hingga fajar abad ke-20.', 4.8, 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(33, 'Madilog: Materialisme, Dialektika, Logika', 'Tan Malaka', 'Sastra & Filsafat', 2014, 'Rak Sosial S-03', 4, 4, 'Karya filsafat monumentil Tan Malaka yang memandu bangsa Indonesia untuk berpikir rasional dan ilmiah guna melepaskan diri dari mistisisme.', 4.6, 'https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(34, 'Saman', 'Ayu Utami', 'Sastra & Filsafat', 1998, 'Rak Sastra S-10', 4, 4, 'Novel pemenang penghargaan yang membahas tentang seksualitas perempuan, kebebasan, perjuangan buruh, dan represi politik Orde Baru.', 4.5, 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(35, 'Ronggeng Dukuh Paruk', 'Ahmad Tohari', 'Sastra & Filsafat', 2003, 'Rak Sastra S-05', 6, 6, 'Trilogi novel sosiokultural yang mengisahkan Srintil and Rasus dengan latar kehidupan dusun miskin yang luluh lantak akibat konflik politik 1965.', 4.8, 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(36, 'Hujan Bulan Juni: Kumpulan Puisi', 'Sapardi Djoko Damono', 'Sastra & Filsafat', 2015, 'Rak Sastra S-01', 8, 8, 'Koleksi puisi cinta liris paling romantis dan bersahaja dalam sastra Indonesia modern yang penuh kedalaman makna hidup.', 4.9, 'https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(37, 'Berani Tidak Disukai', 'Ichiro Kishimi & Fumitake Koga (Terjemahan)', 'Pengembangan Diri', 2019, 'Rak Psikologi P-01', 9, 9, 'Panduan psikologi Adlerian yang mengajari kita melepaskan diri dari penilaian orang lain, berdamai dengan trauma, dan meraih kebebasan sejati.', 4.8, 'https://images.unsplash.com/photo-1490730141103-6cac27aaab94?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(38, 'Grit: Kekuatan Passion dan Kegigihan', 'Angela Duckworth (Terjemahan)', 'Pengembangan Diri', 2018, 'Rak Psikologi P-03', 5, 4, 'Menunjukkan bahwa kunci kesuksesan jangka panjang bukanlah bakat murni, melainkan kombinasi istimewa antara ketabahan dan hasrat (Grit).', 4.6, 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(39, 'Man\'s Search for Meaning', 'Viktor E. Frankl (Terjemahan)', 'Pengembangan Diri', 2017, 'Rak Psikologi P-06', 6, 6, 'Buku legendaris tulisan psikiater penyintas kamp konsentrasi Nazi tentang pentingnya menemukan makna hidup dalam penderitaan terpahit sekalipun.', 4.9, 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(40, 'Think and Grow Rich: Berpikir dan Menjadi Kaya', 'Napoleon Hill (Terjemahan)', 'Pengembangan Diri', 2016, 'Rak Psikologi P-08', 5, 5, 'Formula sukses legendaris yang merangkum kebiasaan orang-orang terkaya di dunia untuk mengubah hasrat mental menjadi kenyataan fisik.', 4.5, 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(41, 'Mindset: Mengubah Pola Pikir untuk Perubahan Besar', 'Carol S. Dweck (Terjemahan)', 'Pengembangan Diri', 2018, 'Rak Psikologi P-02', 7, 6, 'Mengembangkan perbedaan pola pikir tetap (fixed mindset) vs pola pikir berkembang (growth mindset) yang membentuk kesuksesan hidup.', 4.7, 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(42, 'Seni Berbicara di Depan Umum: Public Speaking', 'Dale Carnegie (Terjemahan)', 'Pengembangan Diri', 2015, 'Rak Psikologi P-10', 6, 6, 'Metode praktis mengatasi rasa takut, melatih artikulasi, serta menarik simpati pendengar dalam komunikasi profesional dan interpersonal.', 4.6, 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(43, 'Ikigai: Rahasia Hidup Bahagia & Panjang Umur ala Jepang', 'Héctor García (Terjemahan)', 'Pengembangan Diri', 2019, 'Rak Psikologi P-05', 8, 8, 'Eksplorasi konsep Ikigai, yaitu pertemuan antara hasrat, misi, pekerjaan, dan keahlian untuk menemukan alasan bangun di pagi hari.', 4.7, 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(44, 'Rich Dad Poor Dad: Mengajarkan Keuangan pada Anak', 'Robert T. Kiyosaki (Terjemahan)', 'Bisnis & Keuangan', 2016, 'Rak Bisnis B-01', 8, 8, 'Mengunggap miskonsepsi besar tentang kekayaan, perbedaan aset vs liabilitas, dan bagaimana membiarkan uang bekerja keras untuk kita.', 4.8, 'https://images.unsplash.com/photo-1544377193-33dcf4d68fb5?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(45, 'The Intelligent Investor: Rekomendasi Investasi Nilai', 'Benjamin Graham (Terjemahan)', 'Bisnis & Keuangan', 2018, 'Rak Bisnis B-04', 4, 4, 'Alkitab perdagangan saham legendaris yang memaparkan prinsip value investing demi menghindari jebakan bursa dan risiko pasar besar.', 4.7, 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(46, 'Zero to One: Catatan tentang Startup', 'Peter Thiel (Terjemahan)', 'Bisnis & Keuangan', 2015, 'Rak Bisnis B-02', 5, 5, 'Membahas pentingnya menciptakan inovasi baru yang mengubah monopoli industri dan menciptakan masa depan dari nol menjadi satu.', 4.6, 'https://images.unsplash.com/photo-1507537297725-24a1c029d3ca?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(47, 'The Lean Startup: Memulai Bisnis Modern dengan Efisien', 'Eric Ries (Terjemahan)', 'Bisnis & Keuangan', 2016, 'Rak Bisnis B-05', 6, 6, 'Kerangka manajemen inovatif menggunakan iterasi cepat, Minimum Viable Product (MVP), dan pembelajaran terukur dalam startup.', 4.7, 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(48, 'Good to Great: Mengapa Ada Perusahaan Lompat Kelas', 'Jim Collins (Terjemahan)', 'Bisnis & Keuangan', 2017, 'Rak Bisnis B-07', 3, 3, 'Penelitian mendalam tentang bagaimana perusahaan biasa-biasa saja bertransformasi menjadi perusahaan raksasa yang bertahan puluhan tahun.', 4.6, 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(49, 'Psychology of Money: Pelajaran Abadi tentang Keuangan', 'Morgan Housel (Terjemahan)', 'Bisnis & Keuangan', 2021, 'Rak Bisnis B-10', 10, 9, 'Eksplorasi perilaku emosional manusia terhadap uang, ego, keserakahan, serta cara bijak mengelola kekayaan berkelanjutan.', 4.9, 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?q=80&w=600&auto=format&fit=crop', NULL, NULL),
(50, 'Pemasaran 5.0: Teknologi untuk Kemanusiaan', 'Philip Kotler & Hermawan Kartajaya', 'Bisnis & Keuangan', 2021, 'Rak Bisnis B-03', 5, 5, 'Mengintegrasikan taktik pemasaran manusiawi dengan teknologi mutakhir (AI, big data, AR/VR) untuk memenangkan persaingan bisnis digital.', 4.8, 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=600&auto=format&fit=crop', NULL, NULL);

-- --------------------------------------------------------

-- Struktur dari tabel `loans`
CREATE TABLE IF NOT EXISTS `loans` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `bookId` bigint(20) unsigned NOT NULL,
  `bookTitle` varchar(255) NOT NULL,
  `memberId` varchar(255) NOT NULL,
  `memberName` varchar(255) NOT NULL,
  `borrowDate` date NOT NULL,
  `dueDate` date NOT NULL,
  `returnDate` date DEFAULT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'borrowed',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `bookId` (`bookId`),
  CONSTRAINT `loans_ibfk_1` FOREIGN KEY (`bookId`) REFERENCES `books` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data untuk tabel `loans`
INSERT INTO `loans` (`id`, `bookId`, `bookTitle`, `memberId`, `memberName`, `borrowDate`, `dueDate`, `returnDate`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'Belajar React dan Next.js Modern', 'M-101', 'Achmad Naufal', '2026-06-01', '2026-06-08', '2026-06-07', 'returned', NULL, NULL),
(2, 3, 'Filosofi Teras: Hidup Tenang ala Stoisisme', 'M-101', 'Achmad Naufal', '2026-06-04', '2026-06-11', NULL, 'borrowed', NULL, NULL);
